spring:
  application:
    name: backend-java

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true
