CREATE TABLE sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(255),
    original_url VARCHAR(2048) NOT NULL,
    feed_url VARCHAR(2048),
    strategy_kind VARCHAR(64),
    strategy_config TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    last_success_at TIMESTAMPTZ,
    last_failure_at TIMESTAMPTZ,
    needs_readaptation BOOLEAN NOT NULL DEFAULT FALSE,
    readaptation_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sources_original_url UNIQUE (original_url)
);

CREATE TABLE settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(255) NOT NULL,
    value TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_settings_key UNIQUE (key)
);

CREATE TABLE secret_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(255) NOT NULL,
    encrypted_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_secret_settings_key UNIQUE (key)
);

CREATE TABLE technical_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity VARCHAR(32) NOT NULL DEFAULT 'info',
    subsystem VARCHAR(128) NOT NULL,
    event_code VARCHAR(128) NOT NULL,
    summary TEXT NOT NULL,
    details TEXT,
    source_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_technical_events_source_id FOREIGN KEY (source_id) REFERENCES sources (id)
);
