ALTER TABLE sources
    ADD COLUMN consecutive_failures INTEGER NOT NULL DEFAULT 0;

CREATE TABLE posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id INTEGER NOT NULL,
    canonical_url VARCHAR(2048) NOT NULL,
    title VARCHAR(512) NOT NULL,
    published_at TIMESTAMPTZ,
    raw_content TEXT NOT NULL,
    content_hash VARCHAR(128) NOT NULL,
    ingest_metadata TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_posts_source_id FOREIGN KEY (source_id) REFERENCES sources (id),
    CONSTRAINT uq_posts_canonical_url UNIQUE (canonical_url),
    CONSTRAINT uq_posts_content_hash UNIQUE (content_hash)
);

CREATE TABLE feedback (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    state VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_feedback_post_id FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT uq_feedback_post_id UNIQUE (post_id)
);

CREATE TABLE post_analysis (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    summary_ru TEXT,
    metadata_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_analysis_post_id FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT uq_post_analysis_post_id UNIQUE (post_id)
);

CREATE TABLE preference_profile (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary TEXT,
    metadata_json TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
