CREATE TABLE digests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_type VARCHAR(64) NOT NULL,
    scheduled_for TIMESTAMPTZ NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    recipient_email VARCHAR(512),
    subject VARCHAR(512),
    html_body TEXT,
    metadata_json TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE digest_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    rank_position INTEGER NOT NULL,
    CONSTRAINT fk_digest_items_digest_id FOREIGN KEY (digest_id) REFERENCES digests (id),
    CONSTRAINT fk_digest_items_post_id FOREIGN KEY (post_id) REFERENCES posts (id)
);
