CREATE TABLE read_later (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_read_later_post_id FOREIGN KEY (post_id) REFERENCES posts (id),
    CONSTRAINT uq_read_later_post_id UNIQUE (post_id)
);
