<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.goodnews</groupId>
        <artifactId>good-news-java</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>good-news-contract</artifactId>
    <name>good-news-contract</name>

    <dependencies>
        <dependency>
            <groupId>com.goodnews</groupId>
            <artifactId>good-news-backend</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <classifier>exec</classifier>
                    <mainClass>com.goodnews.backendjava.contract.ContractApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
